name: Main Pipeline

on:
  push:
    branches:
      - feature/**
      - hotfix/**
      - main
  pull_request:
    branches:
      - main
      - develop
      - release

jobs:
  commit-check:
    if: github.event_name == 'push' && (contains(github.ref, 'feature/') || contains(github.ref, 'hotfix/'))
    uses: ./.github/workflows/verify-commit.yml
    secrets: inherit

  lint:
    needs: [commit-check]
    if: |
      always() && 
      (needs.commit-check.result == 'success' || needs.commit-check.result == 'skipped') &&
      (
        (github.event_name == 'push' && (contains(github.ref, 'feature/') || contains(github.ref, 'hotfix/'))) ||
        (github.event_name == 'pull_request' && (
          (contains(github.base_ref, 'develop') && (contains(github.head_ref, 'feature/') || contains(github.head_ref, 'hotfix/'))) ||
          (contains(github.base_ref, 'release') && contains(github.head_ref, 'develop')) ||
          (contains(github.base_ref, 'main') && contains(github.head_ref, 'release'))
        ))
      )
    uses: ./.github/workflows/verify-lint.yml
    secrets: inherit

  unit-tests:
    needs: [lint]
    if: |
      always() && 
      needs.lint.result == 'success' &&
      (
        (github.event_name == 'push' && (contains(github.ref, 'feature/') || contains(github.ref, 'hotfix/'))) ||
        (github.event_name == 'pull_request' && (
          (contains(github.base_ref, 'release') && contains(github.head_ref, 'develop')) ||
          (contains(github.base_ref, 'main') && contains(github.head_ref, 'release'))
        ))
      )
    uses: ./.github/workflows/execute-unit-tests.yml
    secrets: inherit

  integration-tests:
    needs: [lint, unit-tests]
    if: |
      always() && 
      needs.lint.result == 'success' && 
      (needs.unit-tests.result == 'success' || needs.unit-tests.result == 'skipped') &&
      (
        (github.event_name == 'pull_request' && (
          (contains(github.base_ref, 'develop') && (contains(github.head_ref, 'feature/') || contains(github.head_ref, 'hotfix/'))) ||
          (contains(github.base_ref, 'release') && contains(github.head_ref, 'develop')) ||
          (contains(github.base_ref, 'main') && contains(github.head_ref, 'release'))
        ))
      )
    uses: ./.github/workflows/execute-integration-tests.yml
    secrets: inherit