name: Deploy Data Processing Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/DataProcessorService
            git pull origin main

            docker container stop data-processing || true
            docker container rm data-processing || true
            docker image prune -f || true
            docker system prune -f || true

            docker build -t data-processing-img:${{ github.sha }} .

            docker run -d \
              --name data-processing \
              --restart unless-stopped \
              -p 5000:5000 \
              data-processing-img
